# Generated by Django 3.2.6 on 2021-08-15 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField()),
                ('q', models.CharField(max_length=200)),
                ('a', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Quizzes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizID', models.IntegerField()),
                ('questionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question', to='question.qna')),
            ],
        ),
    ]
