# Generated by Django 3.2.6 on 2021-08-30 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionID', models.IntegerField()),
                ('q1', models.CharField(max_length=200)),
                ('q2', models.CharField(max_length=200)),
                ('q3', models.CharField(max_length=200)),
                ('q4', models.CharField(max_length=200)),
                ('a', models.CharField(max_length=2)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizzes',
            name='questionID',
        ),
        migrations.DeleteModel(
            name='QnA',
        ),
        migrations.DeleteModel(
            name='Quizzes',
        ),
    ]
