# Generated by Django 3.2.6 on 2021-09-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_quiz_quizid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quizName',
        ),
        migrations.AddField(
            model_name='question',
            name='quiz',
            field=models.ManyToManyField(blank=True, related_name='questions', to='question.Quiz'),
        ),
    ]
