# Generated by Django 3.2.6 on 2021-09-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20210901_1145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='q1',
            new_name='qa',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q2',
            new_name='qb',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q3',
            new_name='qc',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='q4',
            new_name='qd',
        ),
    ]
