# Generated by Django 3.2.6 on 2021-09-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_auto_20210904_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='numq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
