# Generated by Django 3.2.6 on 2021-09-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_question_numq'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='numq',
        ),
        migrations.AddField(
            model_name='quiz',
            name='numq',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
