# Generated by Django 3.2.6 on 2021-09-23 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20210915_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='numq',
        ),
    ]
