# Generated by Django 3.2.6 on 2021-11-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_auto_20211009_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='average',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='totalAttempts',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='totalScore',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
