# Generated by Django 3.2.6 on 2021-11-08 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_auto_20211104_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='diagram',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
