# Generated by Django 3.2.6 on 2021-11-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_question_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='q5',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=500),
        ),
    ]
