# Generated by Django 3.2.6 on 2021-11-10 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0017_auto_20211110_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='diagram',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
