# Generated by Django 3.2.6 on 2022-01-21 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0019_alter_question_diagram'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.CharField(default=' ', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ansRecord',
            field=models.CharField(default=' ', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tickRecord',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
